name: CI

on:
  push:
    branches: [ master ]

  # Run weekly to keep cache alive.
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10'
    - uses: actions/cache@v3
      name: Caching
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('cabal.project') }}
        restore-keys: |
          ${{ runner.os }}

    - name: Install Debian dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuplot imagemagick

    - uses: diku-dk/install-futhark@v1.1.0
      with:
        version: 'latest'

    - name: Build Haskell
      run: |
        cabal update
        cabal build

    - name: Build site
      run: |
        cabal exec futhark-website clean
        cabal exec futhark-website build

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSHKEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy site
      run: |
        cabal exec futhark-website deploy
